/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AuthenticationGetJwtResponseJwtsAgrimetrics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthenticationGetJwtResponseJwts
 */
public class AuthenticationGetJwtResponseJwtsTest {
    private final AuthenticationGetJwtResponseJwts model = new AuthenticationGetJwtResponseJwts();

    /**
     * Model tests for AuthenticationGetJwtResponseJwts
     */
    @Test
    public void testAuthenticationGetJwtResponseJwts() {
        // TODO: test AuthenticationGetJwtResponseJwts
    }

    /**
     * Test the property 'agrimetrics'
     */
    @Test
    public void agrimetricsTest() {
        // TODO: test agrimetrics
    }

}
