/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AuthenticationGetJwtResponseJwts;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthenticationGetJwtResponse
 */
public class AuthenticationGetJwtResponseTest {
    private final AuthenticationGetJwtResponse model = new AuthenticationGetJwtResponse();

    /**
     * Model tests for AuthenticationGetJwtResponse
     */
    @Test
    public void testAuthenticationGetJwtResponse() {
        // TODO: test AuthenticationGetJwtResponse
    }

    /**
     * Test the property 'jwts'
     */
    @Test
    public void jwtsTest() {
        // TODO: test jwts
    }

}
