/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.File;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DataRequest
 */
public class DataRequestTest {
    private final DataRequest model = new DataRequest();

    /**
     * Model tests for DataRequest
     */
    @Test
    public void testDataRequest() {
        // TODO: test DataRequest
    }

    /**
     * Test the property 'projectName'
     */
    @Test
    public void projectNameTest() {
        // TODO: test projectName
    }

    /**
     * Test the property 'projectManagerName'
     */
    @Test
    public void projectManagerNameTest() {
        // TODO: test projectManagerName
    }

    /**
     * Test the property 'projectManagerEmail'
     */
    @Test
    public void projectManagerEmailTest() {
        // TODO: test projectManagerEmail
    }

    /**
     * Test the property 'datasetId'
     */
    @Test
    public void datasetIdTest() {
        // TODO: test datasetId
    }

    /**
     * Test the property 'datasetName'
     */
    @Test
    public void datasetNameTest() {
        // TODO: test datasetName
    }

    /**
     * Test the property 'geoJsonAOI'
     */
    @Test
    public void geoJsonAOITest() {
        // TODO: test geoJsonAOI
    }

    /**
     * Test the property 'shapefileAOI'
     */
    @Test
    public void shapefileAOITest() {
        // TODO: test shapefileAOI
    }

    /**
     * Test the property 'requestedFormat'
     */
    @Test
    public void requestedFormatTest() {
        // TODO: test requestedFormat
    }

}
