/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EntitlementsDataSet
 */
public class EntitlementsDataSetTest {
    private final EntitlementsDataSet model = new EntitlementsDataSet();

    /**
     * Model tests for EntitlementsDataSet
     */
    @Test
    public void testEntitlementsDataSet() {
        // TODO: test EntitlementsDataSet
    }

    /**
     * Test the property 'read'
     */
    @Test
    public void readTest() {
        // TODO: test read
    }

    /**
     * Test the property 'write'
     */
    @Test
    public void writeTest() {
        // TODO: test write
    }

}
