/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EntitlementsCatalog;
import com.konfigthis.client.model.EntitlementsDataSet;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Entitlements
 */
public class EntitlementsTest {
    private final Entitlements model = new Entitlements();

    /**
     * Model tests for Entitlements
     */
    @Test
    public void testEntitlements() {
        // TODO: test Entitlements
    }

    /**
     * Test the property 'catalog'
     */
    @Test
    public void catalogTest() {
        // TODO: test catalog
    }

    /**
     * Test the property 'dataSet'
     */
    @Test
    public void dataSetTest() {
        // TODO: test dataSet
    }

    /**
     * Test the property 'isAdmin'
     */
    @Test
    public void isAdminTest() {
        // TODO: test isAdmin
    }

}
