/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GeoJSONPoint;
import com.konfigthis.client.model.OutputFormats;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PointSearch
 */
public class PointSearchTest {
    private final PointSearch model = new PointSearch();

    /**
     * Model tests for PointSearch
     */
    @Test
    public void testPointSearch() {
        // TODO: test PointSearch
    }

    /**
     * Test the property 'geometry'
     */
    @Test
    public void geometryTest() {
        // TODO: test geometry
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'outputFormat'
     */
    @Test
    public void outputFormatTest() {
        // TODO: test outputFormat
    }

}
