/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TaxonomyKeywords
 */
public class TaxonomyKeywordsTest {
    private final TaxonomyKeywords model = new TaxonomyKeywords();

    /**
     * Model tests for TaxonomyKeywords
     */
    @Test
    public void testTaxonomyKeywords() {
        // TODO: test TaxonomyKeywords
    }

    /**
     * Test the property 'valueUri'
     */
    @Test
    public void valueUriTest() {
        // TODO: test valueUri
    }

    /**
     * Test the property 'valueLabel'
     */
    @Test
    public void valueLabelTest() {
        // TODO: test valueLabel
    }

    /**
     * Test the property 'sourceUri'
     */
    @Test
    public void sourceUriTest() {
        // TODO: test sourceUri
    }

    /**
     * Test the property 'sourceLabel'
     */
    @Test
    public void sourceLabelTest() {
        // TODO: test sourceLabel
    }

}
