/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Contact for the metadata on this data set
 */
@ApiModel(description = "Contact for the metadata on this data set")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DataSetPatchMetadataContact {
  public static final String SERIALIZED_NAME_ORGANISATION_NAME = "organisationName";
  @SerializedName(SERIALIZED_NAME_ORGANISATION_NAME)
  private String organisationName;

  public static final String SERIALIZED_NAME_INDIVIDUAL_NAME = "individualName";
  @SerializedName(SERIALIZED_NAME_INDIVIDUAL_NAME)
  private String individualName;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS = "emailAddress";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS)
  private String emailAddress;

  /**
   * The role of this contact as it relates to the data set
   */
  @JsonAdapter(RoleEnum.Adapter.class)
 public enum RoleEnum {
    RESOURCEPROVIDER("resourceProvider"),
    
    CUSTODIAN("custodian"),
    
    OWNER("owner"),
    
    USER("user"),
    
    DISTRIBUTOR("distributor"),
    
    ORIGINATOR("originator"),
    
    POINTOFCONTACT("pointOfContact"),
    
    PRINCIPALINVESTIGATOR("principalInvestigator"),
    
    PROCESSOR("processor"),
    
    PUBLISHER("publisher"),
    
    AUTHOR("author");

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RoleEnum fromValue(String value) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RoleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RoleEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RoleEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RoleEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  private RoleEnum role;

  public DataSetPatchMetadataContact() {
  }

  public DataSetPatchMetadataContact organisationName(String organisationName) {
    
    
    
    
    this.organisationName = organisationName;
    return this;
  }

   /**
   * Organisation name for this contact
   * @return organisationName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Organisation name for this contact")

  public String getOrganisationName() {
    return organisationName;
  }


  public void setOrganisationName(String organisationName) {
    
    
    
    this.organisationName = organisationName;
  }


  public DataSetPatchMetadataContact individualName(String individualName) {
    
    
    
    
    this.individualName = individualName;
    return this;
  }

   /**
   * Individual name for this contact
   * @return individualName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Individual name for this contact")

  public String getIndividualName() {
    return individualName;
  }


  public void setIndividualName(String individualName) {
    
    
    
    this.individualName = individualName;
  }


  public DataSetPatchMetadataContact emailAddress(String emailAddress) {
    
    
    
    
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Email address for this contact
   * @return emailAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Email address for this contact")

  public String getEmailAddress() {
    return emailAddress;
  }


  public void setEmailAddress(String emailAddress) {
    
    
    
    this.emailAddress = emailAddress;
  }


  public DataSetPatchMetadataContact role(RoleEnum role) {
    
    
    
    
    this.role = role;
    return this;
  }

   /**
   * The role of this contact as it relates to the data set
   * @return role
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The role of this contact as it relates to the data set")

  public RoleEnum getRole() {
    return role;
  }


  public void setRole(RoleEnum role) {
    
    
    
    this.role = role;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DataSetPatchMetadataContact instance itself
   */
  public DataSetPatchMetadataContact putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataSetPatchMetadataContact dataSetPatchMetadataContact = (DataSetPatchMetadataContact) o;
    return Objects.equals(this.organisationName, dataSetPatchMetadataContact.organisationName) &&
        Objects.equals(this.individualName, dataSetPatchMetadataContact.individualName) &&
        Objects.equals(this.emailAddress, dataSetPatchMetadataContact.emailAddress) &&
        Objects.equals(this.role, dataSetPatchMetadataContact.role)&&
        Objects.equals(this.additionalProperties, dataSetPatchMetadataContact.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organisationName, individualName, emailAddress, role, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataSetPatchMetadataContact {\n");
    sb.append("    organisationName: ").append(toIndentedString(organisationName)).append("\n");
    sb.append("    individualName: ").append(toIndentedString(individualName)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("organisationName");
    openapiFields.add("individualName");
    openapiFields.add("emailAddress");
    openapiFields.add("role");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("organisationName");
    openapiRequiredFields.add("role");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DataSetPatchMetadataContact
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DataSetPatchMetadataContact.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DataSetPatchMetadataContact is not found in the empty JSON string", DataSetPatchMetadataContact.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DataSetPatchMetadataContact.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("organisationName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organisationName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organisationName").toString()));
      }
      if ((jsonObj.get("individualName") != null && !jsonObj.get("individualName").isJsonNull()) && !jsonObj.get("individualName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `individualName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("individualName").toString()));
      }
      if ((jsonObj.get("emailAddress") != null && !jsonObj.get("emailAddress").isJsonNull()) && !jsonObj.get("emailAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `emailAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emailAddress").toString()));
      }
      if (!jsonObj.get("role").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `role` to be a primitive type in the JSON string but got `%s`", jsonObj.get("role").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DataSetPatchMetadataContact.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DataSetPatchMetadataContact' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DataSetPatchMetadataContact> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DataSetPatchMetadataContact.class));

       return (TypeAdapter<T>) new TypeAdapter<DataSetPatchMetadataContact>() {
           @Override
           public void write(JsonWriter out, DataSetPatchMetadataContact value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DataSetPatchMetadataContact read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DataSetPatchMetadataContact instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DataSetPatchMetadataContact given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DataSetPatchMetadataContact
  * @throws IOException if the JSON string is invalid with respect to DataSetPatchMetadataContact
  */
  public static DataSetPatchMetadataContact fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DataSetPatchMetadataContact.class);
  }

 /**
  * Convert an instance of DataSetPatchMetadataContact to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

