/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * GeospatialExtent
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GeospatialExtent {
  public static final String SERIALIZED_NAME_NORTH_BOUND_LATITUDE = "northBoundLatitude";
  @SerializedName(SERIALIZED_NAME_NORTH_BOUND_LATITUDE)
  private Double northBoundLatitude;

  public static final String SERIALIZED_NAME_EAST_BOUND_LONGITUDE = "eastBoundLongitude";
  @SerializedName(SERIALIZED_NAME_EAST_BOUND_LONGITUDE)
  private Double eastBoundLongitude;

  public static final String SERIALIZED_NAME_SOUTH_BOUND_LATITUDE = "southBoundLatitude";
  @SerializedName(SERIALIZED_NAME_SOUTH_BOUND_LATITUDE)
  private Double southBoundLatitude;

  public static final String SERIALIZED_NAME_WEST_BOUND_LONGITUDE = "westBoundLongitude";
  @SerializedName(SERIALIZED_NAME_WEST_BOUND_LONGITUDE)
  private Double westBoundLongitude;

  public GeospatialExtent() {
  }

  public GeospatialExtent northBoundLatitude(Double northBoundLatitude) {
    
    
    
    
    this.northBoundLatitude = northBoundLatitude;
    return this;
  }

  public GeospatialExtent northBoundLatitude(Integer northBoundLatitude) {
    
    
    
    
    this.northBoundLatitude = northBoundLatitude.doubleValue();
    return this;
  }

   /**
   * Get northBoundLatitude
   * @return northBoundLatitude
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getNorthBoundLatitude() {
    return northBoundLatitude;
  }


  public void setNorthBoundLatitude(Double northBoundLatitude) {
    
    
    
    this.northBoundLatitude = northBoundLatitude;
  }


  public GeospatialExtent eastBoundLongitude(Double eastBoundLongitude) {
    
    
    
    
    this.eastBoundLongitude = eastBoundLongitude;
    return this;
  }

  public GeospatialExtent eastBoundLongitude(Integer eastBoundLongitude) {
    
    
    
    
    this.eastBoundLongitude = eastBoundLongitude.doubleValue();
    return this;
  }

   /**
   * Get eastBoundLongitude
   * @return eastBoundLongitude
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getEastBoundLongitude() {
    return eastBoundLongitude;
  }


  public void setEastBoundLongitude(Double eastBoundLongitude) {
    
    
    
    this.eastBoundLongitude = eastBoundLongitude;
  }


  public GeospatialExtent southBoundLatitude(Double southBoundLatitude) {
    
    
    
    
    this.southBoundLatitude = southBoundLatitude;
    return this;
  }

  public GeospatialExtent southBoundLatitude(Integer southBoundLatitude) {
    
    
    
    
    this.southBoundLatitude = southBoundLatitude.doubleValue();
    return this;
  }

   /**
   * Get southBoundLatitude
   * @return southBoundLatitude
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getSouthBoundLatitude() {
    return southBoundLatitude;
  }


  public void setSouthBoundLatitude(Double southBoundLatitude) {
    
    
    
    this.southBoundLatitude = southBoundLatitude;
  }


  public GeospatialExtent westBoundLongitude(Double westBoundLongitude) {
    
    
    
    
    this.westBoundLongitude = westBoundLongitude;
    return this;
  }

  public GeospatialExtent westBoundLongitude(Integer westBoundLongitude) {
    
    
    
    
    this.westBoundLongitude = westBoundLongitude.doubleValue();
    return this;
  }

   /**
   * Get westBoundLongitude
   * @return westBoundLongitude
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Double getWestBoundLongitude() {
    return westBoundLongitude;
  }


  public void setWestBoundLongitude(Double westBoundLongitude) {
    
    
    
    this.westBoundLongitude = westBoundLongitude;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GeospatialExtent instance itself
   */
  public GeospatialExtent putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeospatialExtent geospatialExtent = (GeospatialExtent) o;
    return Objects.equals(this.northBoundLatitude, geospatialExtent.northBoundLatitude) &&
        Objects.equals(this.eastBoundLongitude, geospatialExtent.eastBoundLongitude) &&
        Objects.equals(this.southBoundLatitude, geospatialExtent.southBoundLatitude) &&
        Objects.equals(this.westBoundLongitude, geospatialExtent.westBoundLongitude)&&
        Objects.equals(this.additionalProperties, geospatialExtent.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(northBoundLatitude, eastBoundLongitude, southBoundLatitude, westBoundLongitude, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeospatialExtent {\n");
    sb.append("    northBoundLatitude: ").append(toIndentedString(northBoundLatitude)).append("\n");
    sb.append("    eastBoundLongitude: ").append(toIndentedString(eastBoundLongitude)).append("\n");
    sb.append("    southBoundLatitude: ").append(toIndentedString(southBoundLatitude)).append("\n");
    sb.append("    westBoundLongitude: ").append(toIndentedString(westBoundLongitude)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("northBoundLatitude");
    openapiFields.add("eastBoundLongitude");
    openapiFields.add("southBoundLatitude");
    openapiFields.add("westBoundLongitude");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("northBoundLatitude");
    openapiRequiredFields.add("eastBoundLongitude");
    openapiRequiredFields.add("southBoundLatitude");
    openapiRequiredFields.add("westBoundLongitude");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GeospatialExtent
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GeospatialExtent.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GeospatialExtent is not found in the empty JSON string", GeospatialExtent.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GeospatialExtent.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GeospatialExtent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GeospatialExtent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GeospatialExtent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GeospatialExtent.class));

       return (TypeAdapter<T>) new TypeAdapter<GeospatialExtent>() {
           @Override
           public void write(JsonWriter out, GeospatialExtent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GeospatialExtent read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GeospatialExtent instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GeospatialExtent given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GeospatialExtent
  * @throws IOException if the JSON string is invalid with respect to GeospatialExtent
  */
  public static GeospatialExtent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GeospatialExtent.class);
  }

 /**
  * Convert an instance of GeospatialExtent to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

