/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BoundingBox;
import com.konfigthis.client.model.OutputFormats;
import com.konfigthis.client.model.QueryLayerMetadataResponseLinks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * QueryLayerMetadataResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class QueryLayerMetadataResponse {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_LAYER_ID = "layerId";
  @SerializedName(SERIALIZED_NAME_LAYER_ID)
  private String layerId;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private QueryLayerMetadataResponseLinks links;

  public static final String SERIALIZED_NAME_GEOMETRY = "geometry";
  @SerializedName(SERIALIZED_NAME_GEOMETRY)
  private BoundingBox geometry;

  public static final String SERIALIZED_NAME_TIMES = "times";
  @SerializedName(SERIALIZED_NAME_TIMES)
  private List<OffsetDateTime> times = null;

  public static final String SERIALIZED_NAME_OUTPUT_FORMATS = "outputFormats";
  @SerializedName(SERIALIZED_NAME_OUTPUT_FORMATS)
  private List<OutputFormats> outputFormats = new ArrayList<>();

  public QueryLayerMetadataResponse() {
  }

  public QueryLayerMetadataResponse description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Geospatial Layer", required = true, value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public QueryLayerMetadataResponse layerId(String layerId) {
    
    
    
    
    this.layerId = layerId;
    return this;
  }

   /**
   * Get layerId
   * @return layerId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "97130f06-6242-463f-bf19-0dd6f5a58cfb", required = true, value = "")

  public String getLayerId() {
    return layerId;
  }


  public void setLayerId(String layerId) {
    
    
    
    this.layerId = layerId;
  }


  public QueryLayerMetadataResponse links(QueryLayerMetadataResponseLinks links) {
    
    
    
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public QueryLayerMetadataResponseLinks getLinks() {
    return links;
  }


  public void setLinks(QueryLayerMetadataResponseLinks links) {
    
    
    
    this.links = links;
  }


  public QueryLayerMetadataResponse geometry(BoundingBox geometry) {
    
    
    
    
    this.geometry = geometry;
    return this;
  }

   /**
   * Get geometry
   * @return geometry
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BoundingBox getGeometry() {
    return geometry;
  }


  public void setGeometry(BoundingBox geometry) {
    
    
    
    this.geometry = geometry;
  }


  public QueryLayerMetadataResponse times(List<OffsetDateTime> times) {
    
    
    
    
    this.times = times;
    return this;
  }

  public QueryLayerMetadataResponse addTimesItem(OffsetDateTime timesItem) {
    if (this.times == null) {
      this.times = new ArrayList<>();
    }
    this.times.add(timesItem);
    return this;
  }

   /**
   * Get times
   * @return times
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"2018-01-01T00:00:00.000Z\",\"2019-01-01T00:00:00.000Z\"]", value = "")

  public List<OffsetDateTime> getTimes() {
    return times;
  }


  public void setTimes(List<OffsetDateTime> times) {
    
    
    
    this.times = times;
  }


  public QueryLayerMetadataResponse outputFormats(List<OutputFormats> outputFormats) {
    
    
    
    
    this.outputFormats = outputFormats;
    return this;
  }

  public QueryLayerMetadataResponse addOutputFormatsItem(OutputFormats outputFormatsItem) {
    this.outputFormats.add(outputFormatsItem);
    return this;
  }

   /**
   * Get outputFormats
   * @return outputFormats
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<OutputFormats> getOutputFormats() {
    return outputFormats;
  }


  public void setOutputFormats(List<OutputFormats> outputFormats) {
    
    
    
    this.outputFormats = outputFormats;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the QueryLayerMetadataResponse instance itself
   */
  public QueryLayerMetadataResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryLayerMetadataResponse queryLayerMetadataResponse = (QueryLayerMetadataResponse) o;
    return Objects.equals(this.description, queryLayerMetadataResponse.description) &&
        Objects.equals(this.layerId, queryLayerMetadataResponse.layerId) &&
        Objects.equals(this.links, queryLayerMetadataResponse.links) &&
        Objects.equals(this.geometry, queryLayerMetadataResponse.geometry) &&
        Objects.equals(this.times, queryLayerMetadataResponse.times) &&
        Objects.equals(this.outputFormats, queryLayerMetadataResponse.outputFormats)&&
        Objects.equals(this.additionalProperties, queryLayerMetadataResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, layerId, links, geometry, times, outputFormats, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryLayerMetadataResponse {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    layerId: ").append(toIndentedString(layerId)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    geometry: ").append(toIndentedString(geometry)).append("\n");
    sb.append("    times: ").append(toIndentedString(times)).append("\n");
    sb.append("    outputFormats: ").append(toIndentedString(outputFormats)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("layerId");
    openapiFields.add("links");
    openapiFields.add("geometry");
    openapiFields.add("times");
    openapiFields.add("outputFormats");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("description");
    openapiRequiredFields.add("layerId");
    openapiRequiredFields.add("links");
    openapiRequiredFields.add("geometry");
    openapiRequiredFields.add("outputFormats");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to QueryLayerMetadataResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!QueryLayerMetadataResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QueryLayerMetadataResponse is not found in the empty JSON string", QueryLayerMetadataResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : QueryLayerMetadataResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("layerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `layerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("layerId").toString()));
      }
      // validate the required field `links`
      QueryLayerMetadataResponseLinks.validateJsonObject(jsonObj.getAsJsonObject("links"));
      // validate the required field `geometry`
      BoundingBox.validateJsonObject(jsonObj.getAsJsonObject("geometry"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("times") != null && !jsonObj.get("times").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `times` to be an array in the JSON string but got `%s`", jsonObj.get("times").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("outputFormats") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("outputFormats").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `outputFormats` to be an array in the JSON string but got `%s`", jsonObj.get("outputFormats").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QueryLayerMetadataResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QueryLayerMetadataResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QueryLayerMetadataResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QueryLayerMetadataResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<QueryLayerMetadataResponse>() {
           @Override
           public void write(JsonWriter out, QueryLayerMetadataResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public QueryLayerMetadataResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             QueryLayerMetadataResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of QueryLayerMetadataResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of QueryLayerMetadataResponse
  * @throws IOException if the JSON string is invalid with respect to QueryLayerMetadataResponse
  */
  public static QueryLayerMetadataResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QueryLayerMetadataResponse.class);
  }

 /**
  * Convert an instance of QueryLayerMetadataResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

