/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Relationship
 */
@JsonAdapter(Relationship.Adapter.class)public enum Relationship {
  
  NARROWER("narrower"),
  
  BROADER("broader");

  private String value;

  Relationship(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Relationship fromValue(String value) {
    for (Relationship b : Relationship.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Relationship> {
    @Override
    public void write(final JsonWriter jsonWriter, final Relationship enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Relationship read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Relationship.fromValue(value);
    }
  }
}

