/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GraphApi
 */
@Disabled
public class GraphApiTest {

    private static GraphApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new GraphApi(apiClient);
    }

    /**
     * List all concepts in linked data graph.
     *
     * List All Concepts Available in Agrimetrics Ontology Graph.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listConceptsTest() throws ApiException {
        api.listConcepts()
                .execute();
        // TODO: test validations
    }

}
