/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.io.File;
import com.konfigthis.client.model.GeoJSONPolygon;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShapefileApi
 */
@Disabled
public class ShapefileApiTest {

    private static ShapefileApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ShapefileApi(apiClient);
    }

    /**
     * Receive a shapefile and return GeoJson
     *
     * &gt; :warning: **This is an Agrimetrics internal operation. It relies on information which is not exposed externally.**  Receive a shapefile and return GeoJson for explore page 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void convertToGeoJsonTest() throws ApiException {
        GeoJSONPolygon response = api.convertToGeoJson()
                .execute();
        // TODO: test validations
    }

}
