/*
 * Catalog API
 * This API lists data sets available on Agrimetrics platform.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WfsApi
 */
@Disabled
public class WfsApiTest {

    private static WfsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new WfsApi(apiClient);
    }

    /**
     * Web Feature Service (WFS) query
     *
     * Query the given data set with the OpenGIS® Web Feature Service interface standard 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryDataOpenGisTest() throws ApiException {
        UUID datasetId = null;
        String response = api.queryDataOpenGis(datasetId)
                .execute();
        // TODO: test validations
    }

    /**
     * Web Feature Service (WFS) query
     *
     * Query the given data set with the OpenGIS® Web Feature Service interface standard 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryDataOpenGis_0Test() throws ApiException {
        UUID datasetId = null;
        String response = api.queryDataOpenGis_0(datasetId)
                .execute();
        // TODO: test validations
    }

    /**
     * Web Feature Service (WFS) query
     *
     * Query the given data set with the OpenGIS® Web Feature Service interface standard 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryDataWithOpenGisTest() throws ApiException {
        UUID datasetId = null;
        String response = api.queryDataWithOpenGis(datasetId)
                .execute();
        // TODO: test validations
    }

}
